import PageFooter from "@/components/PageFooter"
import PageHeader from "@/components/PageHeader"
import "@/styles/globals.css"
import localFont from "next/font/local"

import type { Metadata } from "next"
import { Comfortaa, Cormorant_Garamond } from "next/font/google"

const helveticaneue = localFont({
  src: [
    {
      path: "../lib/fonts/HelveticaNeue/HelveticaNeueMedium.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../lib/fonts/HelveticaNeue/HelveticaNeueRegular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-helvetica-neue",
})

const cormorant_garamond = Cormorant_Garamond({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-cormorant-garamond",
})

const comfortaa = Comfortaa({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-comfortaa",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${comfortaa.variable} ${cormorant_garamond.variable} ${helveticaneue.variable}`}
    >
      <body className="bg-gray-400 font-comfortaa">
        <PageHeader />
        {children}
        <PageFooter />
      </body>
    </html>
  )
}
